# Generated by Django 4.0.4 on 2022-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Github', '0002_github_trip_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='trip_number',
        ),
        migrations.AlterField(
            model_name='github',
            name='url',
            field=models.URLField(blank=True, db_index=True, unique=True),
        ),
    ]
