# Generated by Django 4.0.4 on 2022-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Github', '0003_remove_github_trip_number_alter_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='url',
            field=models.URLField(),
        ),
    ]
